// USERS ---------

// USER LOGIN
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// CURRENT USER
export const CURRENT_USER = 'CURRENT_USER';

// GET USERS
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// EDIT USER
export const EDIT_USERS = 'EDIT_USERS';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAILURE = 'EDIT_USERS_FAILURE';

// DELETE USER
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

// ADD USER
export const ADD_USER = 'ADD_USER';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

// ROLES ----------

// GET ROLES
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

// GET ROLE
export const GET_ROLE = 'GET_ROLE';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GET_ROLE_FAILURE';

// ASSIGN ROLE
export const ASSIGN_ROLE = 'ASSIGN_ROLE';
export const ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS';
export const ASSIGN_ROLE_FAILURE = 'ASSIGN_ROLE_FAILURE';

// DELETE ASSIGNED USER ROLE
export const DELETE_ASSIGNED_ROLE = 'DELETE_ASSIGNED_ROLE';
export const DELETE_ASSIGNED_ROLE_SUCCESS = 'DELETE_ASSIGNED_ROLE_SUCCESS';
export const DELETE_ASSIGNED_ROLE_FAILURE = 'DELETE_ASSIGNED_ROLE_FAILURE';

// HOUSEHOLDS ----------

// GET HOUSEHOLDS
export const GET_HOUSEHOLDS = 'GET_HOUSEHOLDS';
export const GET_HOUSEHOLDS_SUCCESS = 'GET_HOUSEHOLDS_SUCCESS';
export const GET_HOUSEHOLDS_FAILURE = 'GET_HOUSEHOLDS_FAILURE';
